exercise 1 - Angular
binarycodexw/eserciziAngularv2.0 pull request #1
Opened 2021-11-08 14:02 UTC by binarycodexw

2021-11-09 09:56 UTC, Giulia-Reas requested changes

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-container/order-container.component.css
> +
questa riga vuota non va bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-container/order-container.component.css
> +
queste righe vuote non vanno bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-container/order-container.component.css
> +
queste righe vuote non vanno bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-container/order-container.component.html
> +
queste righe vuote non vanno bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-detail/order-detail.component.css
> +
questa riga vuota non va bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-detail/order-detail.component.html
> +
questa riga vuota non va bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-list/order-list.component.css
> +
questa riga vuota non va bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-list/order-list.component.css
> +
questa riga vuota non va bene

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-single/order-single.component.css
> +#order-single {
sistema tutte queste righe vuote, puoi inserirne una tra una classe/id/tag e l'altro
p {
.....
}

.pippo {
.....
}

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/order-single/order-single.component.html
> +<div id="order-single">
elimina tutte queste righe vuote

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/user-container/user-container.component.css
> +#user-container {
righe vuote

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/user-container/user-container.component.html
> +<div id="user-container">
righe vuote

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/user-detail/user-detail.component.css
> +#user-detail {
righe vuote

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/user-list/user-list.component.css
> +
righe vuote

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/user-list/user-list.component.html
> +<div id="user-list">
righe vuote

2021-11-09 09:56 UTC, Giulia-Reas commented on src/app/user-single/user-single.component.css
> +
riga vuota

2021-11-09 09:56 UTC, Giulia-Reas commented on src/styles.css
> +
righe vuote

2021-11-18 22:23 UTC, binarycodexw reviewed
Modifiche fatte

2021-11-22 15:11 UTC, Giulia-Reas approved these changes

2021-11-22 15:11 UTC, merged