exercise 2 - Angular
binarycodexw/eserciziAngularv2.0 pull request #2
Opened 2021-11-08 14:06 UTC by binarycodexw

2021-11-09 14:10 UTC, ghost requested changes

2021-11-09 14:10 UTC, ghost commented on src/app/models/model.ts
> +export enum RoleType {
meglio chiamarlo solo Role

2021-11-09 14:10 UTC, ghost commented on src/app/models/model.ts
> +  export interface obj {
le interfacce hanno la prima lettera maiuscola e dovrebbero avere anche un nome significativo, obj non va bene

2021-11-09 14:10 UTC, ghost commented on src/app/models/model.ts
> +  export interface AddressData {
Address, data non serve

2021-11-09 14:10 UTC, ghost commented on src/app/models/model.ts
> +  export interface CompanyData {
Company, data non serve

2021-11-09 14:10 UTC, ghost commented on src/app/models/model.ts
> +    companies?: [CompanyData, CompanyData],
questo è un array di Company, va scritto Company[]

2021-11-09 14:10 UTC, Giulia-Reas commented on src/app/order-list/order-list.component.html
> +<div id="order-list"><p>order-list.component
non puoi mettere i componenti dentro il tag p

2021-11-09 14:10 UTC, Giulia-Reas commented on src/app/user-details/user-details.component.html
> +<ul>
leva tutte le righe vuote

2021-11-09 14:10 UTC, Giulia-Reas commented on src/app/user-details/user-details.component.ts
> +		{
per favore correggi l'indentazione

2021-11-18 23:06 UTC, binarycodexw reviewed
Modifiche esercizio 2 fatte

2021-12-06 15:13 UTC, ghost approved these changes

2021-12-06 15:13 UTC, merged