exercise 3 - Angular
binarycodexw/eserciziAngularv2.0 pull request #3
Opened 2021-11-08 14:07 UTC by binarycodexw

2021-11-09 14:25 UTC, Giulia-Reas requested changes

2021-11-09 14:25 UTC, Giulia-Reas commented on src/app/user-list/user-list.component.html
> +
righe vuote, sistema l'indentazione

2021-11-09 14:25 UTC, Giulia-Reas commented on src/app/user-list/user-list.component.html
> +    <p><img src="{{user.profilePhotoUrl}}"></p>
non mettere un'immagine dentro un tag p

2021-11-09 14:25 UTC, Giulia-Reas commented on src/app/user-list/user-list.component.html
> +    <!--
non lasciare commenti se non strettamente utili

2021-11-18 23:29 UTC, binarycodexw reviewed
Es. 3 modificato

2021-12-20 15:13 UTC, merged